import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import AboutUs from "@/components/About/AboutUs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 // Replace 'YOUR_APP_ID' and 'YOUR_SERVER_URL' with your actual Moralis App ID and Server URL


 return (
    <html lang="en">
      <body className={inter.className}>
       
          <Navbar />
          {children}
          <AboutUs />
        
      </body>
    </html>
 );
}
